### ISSUE TITLE
Capturing updates to old daily files

### ISSUE THREAD

**Issue by prod3000** [Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE#1]
I noticed that Johns Hopkins will go back to old files and update them.  For instance they updated the 04-01-2020.csv file on 4/12 in the csse_covid_19_daily_reports folder.  They changed the Confirmed and Deaths in Hainan, China from 168,-6 to 162,0.  The 04-01-2020.csv file here still says 168,-6.

With your process is it possible to get these changes? If not, your files are still the best out here and I really appreciate what you've done

![change_old_file](https://user-images.githubusercontent.com/63610181/79406546-63bd5b80-7f65-11ea-8677-954221635d67.PNG)

Thanks

**Comment by Lucas-Czarnecki** [comment]
Hi @prod3000 , thank you for your kind words - they are very much appreciated :) 

I have updated the daily reports (March 23rd through April 1st) to reflect the most recent changes from JHU. The 04-01-2020.csv should now be fixed. 

Incidently, JHU updated the 04-01-2020 again just a few hours after you commented! The current data for confirmed, deaths, recovered, active cases in Hainan is now 168, 6, 162, 0: 
![Screenshot_2020-04-16 CSSEGISandData COVID-19](https://user-images.githubusercontent.com/62263095/79492064-aff7b280-7fdc-11ea-998a-f8c183c72928.png)


I try my best to update the files in this repo to reflect the most recent changes from JHU. You will see such changes in the commits, which are named something like "Adjusted Values". If you notice any other problems, please let me know here and I will fix them.

**Comment by prod3000** [comment]
That's awesome! Thank you so much
