### ISSUE TITLE
Clean daily report didn't get updated along with the rest of the data

### ISSUE THREAD

**Issue by wa-sharifk** [Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE#15]
![image](https://user-images.githubusercontent.com/71513537/95117351-6d569d80-0716-11eb-9922-ccaf0d09e7da.png)

**Comment by Lucas-Czarnecki** [comment]
Thank you. I will try to have this fixed before today's update. Unfortunately, the file has become too large to commit. The csv file will, therefore, need to be split and merged on the user's end. (Git LFS presents its own problems). Note, if you are an R user, the .Rdata file contains the same data.

**Comment by wa-sharifk** [comment]
@Lucas-Czarnecki Thanks... I'm OK with split... just needed to know how to proceed.

**Comment by Lucas-Czarnecki** [comment]
Resolved with dcabec5192fe22c5c99a3842e1c5553e0fbefd50. Thanks again.
