### ISSUE TITLE
Daily reports appear to have stopped being generated after 12/31

### ISSUE THREAD

**Issue by wa-sharifk** [Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE#16]
**Overview:**

As a down stream consumer I rely on /csse_covid_19_clean_data/CSSE_DailyReports.Rdata to fuel my PowerBi dash board. One of my users noticed that the last date of reporting was 1/1

I reviewed the R consumption, the raw file and found both to be true as well however, when I went into the daily reports cleaned, I noticed the latest csv file is 12-31-2020. Is there perhaps a date issue with pulling the upstream JHU data?

I additionally reviewed the upstream JHU repo and found that data has been correctly populated there over the last 6 days.

**Asks:**

Please review the ingress code that pulls from JHU's repo and ensure that it's getting the latest files.

**Comment by Lucas-Czarnecki** [comment]
Thanks for this @wa-sharifk. I will look into it today and fix it ASAP.

**Comment by Lucas-Czarnecki** [comment]
Thanks again @wa-sharifk for bringing this issue to my attention. The problem has been fixed with ad45adc346d402cff9a3c6ccd6e00ff09a429a13. Daily reports will resume being updated accordingly in future commits.

**Comment by wa-sharifk** [comment]
@Lucas-Czarnecki Thanks for the super quick response. I greatly appreciate it.
