### ISSUE TITLE
Duplicate data issue

### ISSUE THREAD

**Issue by wa-sharifk** [Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE#17]
**overview**
Between 4/9 & 4/10, size of the data jumped by approx. 50%

**Research:**
COVID-19-CLEANED-JHUCSSE/COVID-19_CLEAN/csse_covid_19_daily_reports_cleaned:

04-09-2021.csv is 567KB
04-10-2021.csv is 1.11MB

Sample data element was chosen for LA, California which appears 1x on 4/9 and appears 2x on 4/10 on lines 865 & 4852. The lines are identical

A review of 04-11-2021.csv indicates the same is happening there as well. 

Im using the aggregated R data file CSSE_DailyReports.Rdata with PowerBi and am receiving 

![image](https://user-images.githubusercontent.com/71513537/125338583-62244400-e31e-11eb-8d22-ba77c8694d00.png)

**Comment by Lucas-Czarnecki** [comment]
Thank you @wa-sharifk. I believe the issue has been resolved.

**Comment by wa-sharifk** [comment]
Yes, it looks good now... Thank you very much
