### ISSUE TITLE
CSSE_DailyReports.Rdata stops at 1/1

### ISSUE THREAD

**Issue by wa-sharifk** [Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE#20]
No additional data is available after 1/1 although there is data present in the JHU repo.

![image](https://user-images.githubusercontent.com/71513537/149007487-b504323c-e535-4234-9ccf-316ae0a2ae50.png)

**Comment by Lucas-Czarnecki** [comment]
Thanks as always @wa-sharifk. I believe the issue is resolved.

**Comment by wa-sharifk** [comment]
Confirmed, I have data up to 1/17 as of this morning (1/18).

@Lucas-Czarnecki Thank you very much.
