### ISSUE TITLE
Data Validation Logs

### ISSUE THREAD

**Issue by MelbourneDeveloper** [Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE#8]
This is a project I've been working on to convert the CSV files to an SQLite database on a daily basis.
https://github.com/MelbourneDeveloper/COVID-19-DB

There are tools that I am building to validate the data. Perhaps these tools could be used to help with your project.

**Comment by Lucas-Czarnecki** [comment]
Thanks. I'll have a look later this week. Cheers.
