### ISSUE TITLE
NOTICE: Folder "COVID-19_RAW" Deprecating

### ISSUE THREAD

**Issue by Lucas-Czarnecki** [Lucas-Czarnecki/COVID-19-CLEANED-JHUCSSE#9]
The folder "COVID-19_RAW" will be removed later this week (on 06-12-2020). This folder was part of an old, and now obsolete, workflow that I had when starting this project but has not been used or updated for two months. The raw data can, of course, still be found on JHU CSSE's repository.

**Comment by stephenobrochta** [comment]
Thank you for creating this repo. I just deleted nearly 150 lines of code full of ugly hacks and replaced with about 15. Cheers.

**Comment by Lucas-Czarnecki** [comment]
@stephenobrochta I am glad to hear that the repo is helpful. Thank you for your kind works. They are much appreciated. All the best.
